### ISSUE TITLE
6.1.0 release?

### ISSUE THREAD

**Issue by jroszkiewicz** [deployphp/distribution#2]
Any chance to release 6.1.0 version?

**Comment by antonmedv** [comment]
Ow, sorry. Forgot about it. =) Will de CI for it.

**Comment by barryvdh** [comment]
* Friendly reminder * ;)

**Comment by jroszkiewicz** [comment]
ping? @antonmedv

**Comment by antonmedv** [comment]
Done!

**Comment by antonmedv** [comment]
Also I'm thinking to rename this repo into `deployer/phar`

**Comment by jroszkiewicz** [comment]
@antonmedv you have my axe ;-)
