### ISSUE TITLE
deployer/dist 6.8, PHP 8.1 => several deprecation logs in CLI

### ISSUE THREAD

**Issue by iammati** [deployphp/distribution#20]
Using (via composer) `deployer/dist:^6.8` and PHP 8.1 results into:
![image](https://user-images.githubusercontent.com/41418763/158081998-17f4f343-ebfd-464e-a82e-56a534a79f9d.png)

those deprecation logs. I _assume_ PHP 8(.1) is supported? `dep deploy` e.g. works just fine

**Comment by antonmedv** [comment]
Upgrade to v7.
