### ISSUE TITLE
Deployer ignores overriden default deploy task commands

### ISSUE THREAD

**Issue by iammati** [deployphp/distribution#21]
Upgrade without issues from v6.8 to v7.0.0-rc.4 with PHP 8.1.3 but I've noticed that the following snippet:

```php
// Main
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:unlock',
    'deploy:shared',
    'deploy:vendors',
    'deploy:symlink',
    'typo3:finish',
    'deploy:unlock',
    'deploy:cleanup',
])->desc('Deploy your project');
```

Is being ignored by deployer and it executes instead the following commands:
![image](https://user-images.githubusercontent.com/41418763/158254600-a3fc48d4-de58-4355-a276-963fb07c28c9.png)

And runs into a locked-state. Note that right after `update_code` it should actually "force" unlock - testing purpose since I was wondering why I kept run into a locked state.

Any ideas to this?

**Comment by antonmedv** [comment]
Please provide full deploy.php. Also run `dep tree deploy` and `dep deploy --plan`, attach outputs.

**Comment by iammati** [comment]
@antonmedv 
![image](https://user-images.githubusercontent.com/41418763/158255939-328d1638-47bd-4e14-b5ff-1dd178971d9d.png)
![image](https://user-images.githubusercontent.com/41418763/158256092-2448988f-5753-4a36-b771-615d78027acc.png)

**Comment by antonmedv** [comment]
So both     'deploy:prepare' and  'deploy:lock' has lock task in it.

**Comment by iammati** [comment]
Oh that fixed it. Does `deploy:prepare` performs since v7 automatically a lock? Had to use that at least in v6

**Comment by antonmedv** [comment]
It's new API, all other recipes uses prepare as well.
