### ISSUE TITLE
Use "replace" in composer.json

### ISSUE THREAD

**Issue by schmengler** [deployphp/distribution#6]
What do you think about adding `replace` to `composer.json`?
```
replace: {
  "deployer/deployer": "self.version"
}
```

Then it's possible to install additional packages that require Deployer, but still use `deployer/dist` in a project while avoiding dependency conflicts.

**Comment by antonmedv** [comment]
Will be cool.

**Comment by schmengler** [comment]
![one year later...](https://i.pinimg.com/originals/5b/cf/40/5bcf40ed6706a406e96e7c590f799e96.jpg)
